language: php

sudo: required

# Only run test when committing to 1.x branch.
branches:
  only:
    - 1.x

env:
  global:
    - DEVSHOP_VERSION=1.x
    - SITE_HOSTS='dev.drup.devshop.travis dev.projectname.devshop.travis live.projectname.devshop.travis testenv.drpl8.devshop.travis'

  matrix:
  - test="Upgrade"
    COMMAND="robo up --test-upgrade"
    UPGRADE_FROM_VERSION="1.0.0-beta10"

  - test="Install with Docker"
    COMMAND="robo up --test"

  - test="Install with Ansible on Ubuntu 14.04 with Apache"
    COMMAND="robo up --mode=install.sh --test"

#  - test="Install with Ansible on Ubuntu 14.04 with NGINX"
#    COMMAND="robo up --mode=install.sh --test --install-sh-options='--server-webserver=nginx'"

  - test="Install with Ansible on CentOS 7"
    COMMAND="robo up --mode=install.sh --install-sh-image=geerlingguy/docker-centos7-ansible --test"

    
services:
  - docker

before_install:
  - pwd
  - env

  # Install Robo
  - wget https://github.com/consolidation/Robo/releases/download/1.0.5/robo.phar
  - sudo mv robo.phar /usr/local/bin/robo
  - sudo chmod +x /usr/local/bin/robo

  # Install Drush
  - wget https://github.com/drush-ops/drush/releases/download/8.1.9/drush.phar
  - sudo mv drush.phar /usr/local/bin/drush
  - sudo chmod +x /usr/local/bin/drush

  # Clone devshop
  - cd ..
  - git clone http://github.com/opendevshop/devshop
  - cd devshop
  - git checkout -qf ${DEVSHOP_VERSION}
  - git status
  - pwd
  - cp build-devmaster-travis-forks.make.yml build-devmaster-dev.make.yml
  - cat build-devmaster-dev.make.yml

  # Prepare devshop CLI.
  - composer install

script:
  - ${COMMAND} -n

#  - container_id=$(mktemp)
#    # Run container in detached state
#  - 'sudo docker run --detach --name devshop_container --volume="${PWD}/devshop":/usr/share/devshop:rw --volume="${PWD}":/usr/share/devshop/devmaster:rw ${run_opts} -h devshop.travis --add-host "${SITE_HOSTS}":127.0.0.1 ${distribution}-${version}:ansible "${init}" > "${container_id}"'
#
#  # Install script.
#  - 'sudo docker exec devshop_container env TRAVIS=true TERM=xterm TRAVIS_BRANCH=$TRAVIS_BRANCH TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG DEVSHOP_UPGRADE_TO_VERSION=$DEVSHOP_UPGRADE_TO_VERSION TRAVIS_PULL_REQUEST_BRANCH=$TRAVIS_PULL_REQUEST_BRANCH ${install_command} --makefile=/usr/share/devshop/devmaster/build-devmaster-test.make'
#
#  # Hostmaster Status
#  - 'sudo docker exec devshop_container env TERM=xterm sudo su - aegir -c "drush @hostmaster status"'
#
#  # Turn off hosting queued, and the hosting task queue.
#  - 'sudo docker exec devshop_container env sudo su - aegir -c "drush @hostmaster dis hosting_queued -y -v"'
#  - 'sudo docker exec devshop_container env sudo su - aegir -c "drush @hostmaster vset hosting_queue_tasks_enabled 0 -y"'
#
#  # Build and Run Tests
#  - 'sudo docker exec devshop_container env TERM=xterm sudo su - -c "cd /usr/share/devshop/tests && composer update"'
#  - 'sudo docker exec devshop_container env TERM=xterm sudo su - aegir -c "devshop devmaster:test"'
#
#  # Stop container.
#  - 'sudo docker stop devshop_container'
